// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvbrvjaomvrtgprrgmoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2YnJ2amFvbXZydGdwcnJnbW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTM4OTAsImV4cCI6MjA2OTYyOTg5MH0.A1HNDUZp37o5469flBiaOs2_7QC1atogRmwGmu9AAzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});